
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import subprocess
from tkinter import ttk
import sqlite3

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\houtp\OneDrive\Desktop\Final2\View")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def open_login():
    global window
    subprocess.Popen(["python", "Login.py"])
    window.destroy()


def load_reservations(treeview):
    # Clear existing items in the Treeview
    for item in treeview.get_children():
        treeview.delete(item)

    # Connect to the database
    conn = sqlite3.connect('reservation.db')
    cursor = conn.cursor()

    # Fetch data
    cursor.execute("SELECT * FROM reservations")
    rows = cursor.fetchall()

    # Insert data into the Treeview
    for row in rows:
        treeview.insert("", "end", values=row)

    conn.close()

window = Tk()

window.geometry("1728x1117")
window.configure(bg = "#EBEBEB")


canvas = Canvas(
    window,
    bg = "#EBEBEB",
    height = 1117,
    width = 1728,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=open_login,
    relief="flat"
)
button_1.place(
    x=1366.0,
    y=873.0,
    width=213.0,
    height=78.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    1456.5,
    350.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=1317.0,
    y=330.0,
    width=279.0,
    height=38.0
)

tree_frame = ttk.Frame(window)
tree_frame.place(x=86, y=250, width=1200, height=600)  

#  display reservation data
columns = ("Name", "Email", "User ID", "Phone Number", "Room Number", "Check-in Date", "Check-out Date")
treeview = ttk.Treeview(tree_frame, columns=columns, show="headings")
treeview.pack(side="left", fill="both", expand=True)


for col in columns:
    treeview.heading(col, text=col)
    treeview.column(col, width=150)  

# Add vertical scrollbar
scrollbar = ttk.Scrollbar(tree_frame, orient="vertical", command=treeview.yview)
scrollbar.pack(side="right", fill="y")
treeview.configure(yscrollcommand=scrollbar.set)

# Load reservations into the Treeview when the window opens
load_reservations(treeview)


canvas.create_rectangle(
    -1.0,
    1015.0,
    375.0,
    1016.0,
    fill="#000000",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    697.0,
    227.0,
    image=image_image_1
)

canvas.create_text(
    86.0,
    156.0,
    anchor="nw",
    text="View Reservations",
    fill="#000000",
    font=("Istok Web", 70 * -1)
)
window.resizable(False, False)
window.mainloop()
